version: "3"
services:
  adaxtech_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/srv/adaxtech
      - /srv/adaxtech/node_modules
    container_name: adaxtech_dev
    ports:
      - 3004:3000
  adaxtech_staging:
    build:
      context: .
      dockerfile: Dockerfile.staging
    # volumes:
      # - C:\Users\aaron\certs:/etc/nginx/certs # Windows path
      # - /etc/nginx/certs:/etc/nginx/certs # Unix path
    container_name: adaxtech_staging
    ports:
      - 8000:80
      - 443:443
  adaxtech:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
      # - C:\Users\aaron\certs:/etc/nginx/certs # Windows path
      # - /etc/nginx/certs:/etc/nginx/certs # Unix path
    container_name: adaxtech
    ports:
      - 8000:80
      - 443:443